openapi: 3.0.0
info:
  title: medbot-llm-search
  version: 1.0.12
  description: API for MedBot generation extension

servers:
  - url: https://medbot-llm-search.1gpmytaegikv.us-south.codeengine.appdomain.cloud
    description: IBM Cloud Code Engine
paths:
  /generate_response:
    post:
      summary: Generate MedBot response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_question:
                  type: string
                  example: "What does my medication for this visit do?"
                prescription_info:
                  type: array
                  items:
                    type: string
                  example: ["Methotrexate", "Ibuprofen", "Folic Acid"]
                visit_info:
                  type: array
                  items:
                    type: string
                  example: ["Arthritis"]
                patient_id:
                  type: integer
                  example: 1
                visit_id:
                  type: integer
                  example: 1
                intent:
                  type: string
                  enum: [medicine, disease, general]
                additional_info:
                  type: array
                  items:
                    type: string
                  example: ["smoker", "seafood allergy", "nut allergy", "pregnant"]
                history: 
                  type: array
                  items:
                    type: object
                    properties:
                      user_question:
                        type: string
                      response:
                        type: string
                  example: [{"user_question": "What does my medication for this visit do?", "response": "Methotrexate is a medication used to treat arthritis. It works by suppressing the immune system and reducing inflammation."}]
              required:
                - user_question
                - prescription_info
                - visit_info
                - patient_id
                - visit_id
                - intent
                - additional_info
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: object
                    properties:
                      text:
                        type: string
                        example: "\n\nBased on the information provided, it seems that you have been diagnosed with Rheumatoid Arthritis (RA). Here are some next steps for you:\n\n1. Continue taking your prescribed medications, including Methotrexate, Ibuprofen, and Folic Acid. These medications aim to control your RA symptoms and prevent joint damage.\n2. Schedule regular check-ups with your rheumatologist to monitor your condition and adjust your treatment plan as needed.\n3. Engage in physical therapy and occupational therapy to improve your mobility, strength, and overall function.\n4. Explore non-pharmacological methods to manage your pain, such as heat and cold therapy, and consider using assistive devices like splints.\n5. If your symptoms are not controlled by standard therapy, your rheumatologist may recommend biologic agents, which are expensive and reserved for severe cases.\n6. Make lifestyle modifications to improve your overall health, such as quitting smoking, getting adequate rest, exercising regularly, and maintaining a healthy body weight.\n\nRemember, it's essential to follow your healthcare provider's advice and recommendations to manage your RA effectively. If you have any questions or concerns, don't hesitate to discuss them with your rheumatologist.\n\nPlease note that this information is based on the provided context and may not cover all possible aspects of your condition or treatment. Always consult with a healthcare professional for personalized advice.\n\n[Note: The improved response provides a more detailed and personalized explanation of the next steps for managing Rheumatoid Arthritis, taking into account the prescribed medications, regular check-ups, physical therapy, non-pharmacological methods, biologic agents, and lifestyle modifications.]"
                      sources:
                        type: array
                        items:
                          type: string
                        example: ["https://www.ttsh.com.sg/Patients-and-Visitors/Pages/Find-Conditions-and-Treatments-Details.aspx?condition=Rheumatoid-Arthritis", "https://www.ttsh.com.sg/Patients-and-Visitors/Medical-Services/Pharmacy/Documents/Pharmacy/PIL/PIL_by_Drug/Methotrexate_RAI_.pdf"]
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /get_patient:
    post:
      summary: Retrieve patient information
      description: Retrieve patient information from IBM Cloudant based on visit_id and patient_id.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                patient_id:
                  type: integer
                visit_id:
                  type: integer
      responses:
        '200':
          description: Successfully retrieved patient information
          content:
            application/json:
              schema:
                type: object
                properties:
                  visit_id:
                    type: integer
                  prescription_info:
                    type: array
                    items:
                      type: string
                  visit_info:
                    type: array
                    items:
                      type: string
                  patient_id:
                    type: integer
                  NRIC:
                    type: string
                  first_name:
                    type: string
                  last_name:
                    type: string
                  email:
                    type: string
                  additional_info:
                    type: array
                    items:
                      type: string
        '400':
          description: Invalid request
        '500':
          description: Internal server error